Java script
faisalabdulkadir/html pull request #12
Opened 2018-07-06 14:09 UTC by faisalabdulkadir

Javascipt coding

2018-07-07 21:31 UTC, musamusa requested changes

2018-07-07 21:31 UTC, musamusa commented on javaScript.html
> +      demo.getElementById("demo").innerHTML="This is a cool Java script stuff";
did you try this? did it work?
I believe you need to declare `demo` first before you can use. something like the code below:
```
var demo = document.getElementById('demo');
demo.innerHTML  = 'This is a cool Java script stuff';
```

2018-07-08 17:26 UTC, faisalabdulkadir commented on javaScript.html
> +      demo.getElementById("demo").innerHTML="This is a cool Java script stuff";
Thank you Boss for the feedback. code has been corrected. its suppose to be document.getElementById("demo").innerHTML="This is a cool Java script stuff";
Am actually tying to change the content of the paragraph element in HTML with javascript using the id

2018-07-08 17:35 UTC, faisalabdulkadir reviewed
Changes have been effected Sir. The concept was to actually change HTML elements and access some attributes using javaScript linking the two parts together using the ID.

2018-07-13 05:06 UTC, musamusa approved these changes

2018-07-13 19:57 UTC, merged